Code/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learn.urls", namespace="event_management")),
    path("vulture/", include("vulture.urls", namespace="vulture")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls", namespace="members")),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )


admin.site.site_header = "Codemy"
admin.site.site_title = "Codemy.com"
admin.site.index_title = "Learn from codemy"

learn/urls.py
from django.urls import path

from learn.view.view_calendar import calenderMonthView
from learn.view.view_event import event_add, event_delete, event_list, event_read
from learn.view.view_event import event_update
from learn.view.view_participant import participant_add, participant_delete
from learn.view.view_participant import participant_list, participant_read
from learn.view.view_participant import participant_update
from learn.view.view_venue import venue_add, venue_delete, venue_list, venue_read
from learn.view.view_venue import venue_update
from learn.view.view_venue_exports import export_venue_csv, export_venue_pdf
from learn.view.view_venue_exports import export_venue_txt
from learn.views import APIresponse, index, search

app_name = "learn"

urlpatterns = [
    # Home page
    path(
        "",
        index,
        name="index",
    ),
    path(
        "search",
        search,
        name="search",
    ),
    # Venues
    path(
        "venue_add",
        venue_add,
        name="venue_add",
    ),
    path(
        "venue_list",
        venue_list,
        name="venue_list",
    ),
    path(
        "venue_read/<uuid:venue_id>",
        venue_read,
        name="venue_read",
    ),
    path(
        "venue_update/<uuid:venue_id>",
        venue_update,
        name="venue_update",
    ),
    path(
        "venue_delete/<uuid:venue_id>",
        venue_delete,
        name="venue_delete",
    ),
    # Events
    path(
        "event_add",
        event_add,
        name="event_add",
    ),
    path(
        "event_list",
        event_list,
        name="event_list",
    ),
    path(
        "event_read/<uuid:event_id>",
        event_read,
        name="event_read",
    ),
    path(
        "event_update/<uuid:event_id>",
        event_update,
        name="event_update",
    ),
    path(
        "event_delete/<uuid:event_id>",
        event_delete,
        name="event_delete",
    ),
    # Participants
    path(
        "participant_add",
        participant_add,
        name="participant_add",
    ),
    path(
        "participant_list",
        participant_list,
        name="participant_list",
    ),
    path(
        "participant_read/<uuid:participant_id>",
        participant_read,
        name="participant_read",
    ),
    path(
        "participant_update/<uuid:participant_id>",
        participant_update,
        name="participant_update",
    ),
    path(
        "participant_delete/<uuid:participant_id>",
        participant_delete,
        name="participant_delete",
    ),
    # Export Events
    path(
        "export_venues",
        export_venue_txt,
        name="export_venues",
    ),
    path(
        "export_venues_csv",
        export_venue_csv,
        name="export_venues_csv",
    ),
    path(
        "export_venues_pdf",
        export_venue_pdf,
        name="export_venues_pdf",
    ),
    # Calendar Related Views
    path(
        "calender",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "calender/<int:year>/<int:month>",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "api",
        APIresponse,
        name="api",
    ),
]

members/urls.py
from django.urls import path

from members.views import login_user, logout_user, register_user

app_name = "members"

urlpatterns = [
    path("register_user", register_user, name="register_user"),
    path("login", login_user, name="login"),
    path("logout", logout_user, name="logout"),
]

learn/models.py
# from django.db import models

# Create your models here.

learn/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render

from learn.model import Event, Venue
from datetime import datetime

# Create your views here.


def index(inbound_request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        render(
            request=inbound_request,
            template_name="learn/index.html",
            context={
                "title": "Codemy",
            },
        )
    )


@login_required(login_url="members:login")
def search(inbound_request: HttpRequest) -> HttpResponse:
    print("Hello Google....")
    if (inbound_request.method == "POST") and (
        search_query := inbound_request.POST.get("searched", False)
    ):
        venues = Venue.objects.filter(
            Q(name__contains=search_query) | Q(address__contains=search_query)
        )

        events = Event.objects.filter(
            Q(name__contains=search_query)
            | Q(description__contains=search_query)
            | Q()
        )
        print(search_query, venues, events)

        return HttpResponse(
            render(
                request=inbound_request,
                template_name="learn/search_results.html",
                context={
                    "title": "Codemy",
                    "venues": venues,
                    "events": events,
                    "no_of_results": len(venues) + len(events),
                },
            )
        )
    return HttpResponseBadRequest(
        content="Bad Request",
    )


def APIresponse(inbound_request:HttpRequest):
    return JsonResponse(
        {"datetime":datetime.now()}
    )

learn/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name='color-scheme' content='dark light' />
        <!-- Bootstrap Files -->
        <link rel="stylesheet" href=" {% static 'bootstrap-css/bootstrap.min.css' %}" />
        <script defer src="{% static 'bootstrap-js/bootstrap.bundle.min.js' %}"></script>
        <!-- Site Icon -->
        <link rel="shortcut icon" href=" {% static 'favicon.svg' %}" type="image/x-icon" />
        <!-- Custom CSS Files -->
        {% block stylesheets %}
        <!--  -->
        {% endblock stylesheets %}
        <!-- Site Title -->
        <title>{{title}}</title>
    </head>
    <body data-bs-theme="dark" style="user-select: none;">
        {% include "navbar.html" %}
        <div>
            {% if messages %}
                <!--  -->
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <!--  -->
            {% endif %}
        </div>
        <div class="mainContent">
            {% block main-content %}
            <!--  -->
            {% endblock main-content %}
        </div>
        {% block footer %}
        <!--  -->
        {% endblock footer %}
    </body>
</html>

learn/templates/navbar.html
{% load static %}
<!--  -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learn:index' %}">
            <img
                src="{% static 'favicon.svg' %}"
                alt="Logo"
                width="60"
                height="48"
                class="d-inline-block align-text-top"
            />
        </a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learn:viewCalender' %}"> Calender </a>
                </li>
                <!--  -->
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="{% url 'learn:venue_list' %}"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Venues
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'learn:venue_list' %}">View Venues</a></li>
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'learn:venue_add' %}">Add Venue</a></li>
                        {% endif %}
                    </ul>
                </li>
                <!--  -->
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Events
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'learn:event_list' %}">View Events</a></li>
                        <li><a class="dropdown-item" href="{% url 'learn:event_add' %}">Add Event</a></li>
                    </ul>
                </li>
                {% endif %}
                <!-- Participants -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learn:participant_list' %}"> Guests </a>
                </li>
                <!-- Login Logout -->
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        User
                    </a>
                    {% if user.is_authenticated %}
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'members:logout' %}"> Logout </a></li>
                    </ul>
                    {% else %}
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'members:login' %}"> Login </a></li>
                        <li><a class="dropdown-item" href="{% url 'members:register_user' %}"> Register </a></li>
                    </ul>
                    {% endif %}
                </li>
                <!-- Search -->
            </ul>

            <form class="d-flex" role="search" method="post" action="{% url 'learn:search' %}">
                {% csrf_token %}
                <input
                    class="form-control me-2"
                    type="search"
                    name="searched"
                    placeholder="Search"
                    aria-label="Search"
                />
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>