Code/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learn.urls", namespace="event_management")),
    path("vulture/", include("vulture.urls", namespace="vulture")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls", namespace="members")),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )


admin.site.site_header = "Codemy"
admin.site.site_title = "Codemy.com"
admin.site.index_title = "Learn from codemy"

learn/urls.py
from django.urls import path

from learn.view.view_calendar import calenderMonthView
from learn.view.view_event import event_add, event_delete, event_list, event_read
from learn.view.view_event import event_update
from learn.view.view_participant import participant_add, participant_delete
from learn.view.view_participant import participant_list, participant_read
from learn.view.view_participant import participant_update
from learn.view.view_venue import venue_add, venue_delete, venue_list, venue_read
from learn.view.view_venue import venue_update
from learn.view.view_venue_exports import export_venue_csv, export_venue_pdf
from learn.view.view_venue_exports import export_venue_txt
from learn.views import APIresponse, index, search

app_name = "learn"

urlpatterns = [
    # Home page
    path(
        "",
        index,
        name="index",
    ),
    path(
        "search",
        search,
        name="search",
    ),
    # Venues
    path(
        "venue_add",
        venue_add,
        name="venue_add",
    ),
    path(
        "venue_list",
        venue_list,
        name="venue_list",
    ),
    path(
        "venue_read/<uuid:venue_id>",
        venue_read,
        name="venue_read",
    ),
    path(
        "venue_update/<uuid:venue_id>",
        venue_update,
        name="venue_update",
    ),
    path(
        "venue_delete/<uuid:venue_id>",
        venue_delete,
        name="venue_delete",
    ),
    # Events
    path(
        "event_add",
        event_add,
        name="event_add",
    ),
    path(
        "event_list",
        event_list,
        name="event_list",
    ),
    path(
        "event_read/<uuid:event_id>",
        event_read,
        name="event_read",
    ),
    path(
        "event_update/<uuid:event_id>",
        event_update,
        name="event_update",
    ),
    path(
        "event_delete/<uuid:event_id>",
        event_delete,
        name="event_delete",
    ),
    # Participants
    path(
        "participant_add",
        participant_add,
        name="participant_add",
    ),
    path(
        "participant_list",
        participant_list,
        name="participant_list",
    ),
    path(
        "participant_read/<uuid:participant_id>",
        participant_read,
        name="participant_read",
    ),
    path(
        "participant_update/<uuid:participant_id>",
        participant_update,
        name="participant_update",
    ),
    path(
        "participant_delete/<uuid:participant_id>",
        participant_delete,
        name="participant_delete",
    ),
    # Export Events
    path(
        "export_venues",
        export_venue_txt,
        name="export_venues",
    ),
    path(
        "export_venues_csv",
        export_venue_csv,
        name="export_venues_csv",
    ),
    path(
        "export_venues_pdf",
        export_venue_pdf,
        name="export_venues_pdf",
    ),
    # Calendar Related Views
    path(
        "calender",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "calender/<int:year>/<int:month>",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "api",
        APIresponse,
        name="api",
    ),
]

members/urls.py
from django.urls import path

from members.views import login_user, logout_user, register_user

app_name = "members"

urlpatterns = [
    path("register_user", register_user, name="register_user"),
    path("login", login_user, name="login"),
    path("logout", logout_user, name="logout"),
]

learn/models.py
# from django.db import models

# Create your models here.

learn/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render

from learn.model import Event, Venue
from datetime import datetime

# Create your views here.


def index(inbound_request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        render(
            request=inbound_request,
            template_name="learn/index.html",
            context={
                "title": "Codemy",
            },
        )
    )


@login_required(login_url="members:login")
def search(inbound_request: HttpRequest) -> HttpResponse:
    print("Hello Google....")
    if (inbound_request.method == "POST") and (
        search_query := inbound_request.POST.get("searched", False)
    ):
        venues = Venue.objects.filter(
            Q(name__contains=search_query) | Q(address__contains=search_query)
        )

        events = Event.objects.filter(
            Q(name__contains=search_query)
            | Q(description__contains=search_query)
            | Q()
        )
        print(search_query, venues, events)

        return HttpResponse(
            render(
                request=inbound_request,
                template_name="learn/search_results.html",
                context={
                    "title": "Codemy",
                    "venues": venues,
                    "events": events,
                    "no_of_results": len(venues) + len(events),
                },
            )
        )
    return HttpResponseBadRequest(
        content="Bad Request",
    )


def APIresponse(inbound_request:HttpRequest):
    return JsonResponse(
        {"datetime":datetime.now()}
    )

learn/templates/learn/Event/create.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="{% static 'CSS/formcontrol.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<!--  -->
{% if user.is_authenticated %}
<h2>Add event</h2>
<br />
<br />
{% if is_submitted %}
<p>Form Submitted Successfully...</p>
{% else %}
<div class="userform">
    <form action="{% url 'learn:event_add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form.as_div}}
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endif %}
{% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %}
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %}
<!--  -->
{% endblock footer %}

learn/templates/learn/Event/read.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
{% if user.is_authenticated %}
<h3>{{event.name}}</h3>
<p>{{event.description}}</p>

<p>Event Organized By {{event.event_manager.username.title}}</p>
<p>
    {{ event.event_date|date:"d-M-Y" }} {{ event.event_date|time:"h:i A" }} at
    <a href="{% url 'learn:venue_read' event.venue.id %}"> {{event.venue.name.title}} </a>
</p>
<hr />
<ul>
    {% for guest in event.participants.all %}
    <li>
        <a href="{% url 'learn:participant_read' guest.id %}"> {{guest.firstname}} </a>
    </li>
    {% endfor %}
</ul>

{% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %}
<hr />
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %} {% endblock footer %}

learn/templates/learn/Event/read_all.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<h2>Events</h2>
{% for event in events %}
<h3><a href="{% url 'learn:event_read' event.id %}"> {{event.name}} </a> </h3>
<p class="fs-6">{{ event.event_date|date:"d-M-Y" }} {{ event.event_date|time:"h:i A" }}</p>
<p>{{event.description}}</p>
{% if event.event_manager%}
<p>- {{event.event_manager.first_name|title}} {{event.event_manager.last_name|title}}</p>
{% endif %}
{% if user.is_authenticated %}


{% if user == event.event_manager %}
<div style="display: flex; justify-content: flex-start; align-items: center">
    <div class="col">
        <a href="{% url 'learn:event_update' event.id %}">
            <button class="btn btn-secondary">Update</button>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'learn:event_delete' event.id %}">
            <button class="btn btn-danger">Delete</button>
        </a>
    </div>
</div>
<hr />
{% endif %}
{% endif %}
{% endfor %}
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %} {% endblock footer %}

learn/templates/learn/Event/update.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="{% static 'CSS/formcontrol.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<!--  -->
{% if user.is_authenticated %}
{% if user == event.event_manager %}
<h2>Update Event</h2>
<br />
<div class="userform">
    <form action="{% url 'learn:event_update' event.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form.as_div}}
        <input class="btn btn-primary" type="submit" value="Update" />
    </form>
</div>
{% else%}
<p>Access Denied</p>
<p>
    Only
    <strong> Event Manager </strong>
    can update Event.
</p>
{% endif %} {% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %}
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %}
<!--  -->
{% endblock footer %}