Code/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learn.urls", namespace="event_management")),
    path("vulture/", include("vulture.urls", namespace="vulture")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls", namespace="members")),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )


admin.site.site_header = "Codemy"
admin.site.site_title = "Codemy.com"
admin.site.index_title = "Learn from codemy"

vulture/urls.py
from django.urls import include, path

from .views import index

app_name = "vulture"
urlpatterns = [
    path("", index, name="index"),
]

vulture/models.py
from django.db import models

# Create your models here.

vulture/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
import json


# Create your views here.
def index(inbound_request: HttpRequest, *args, **kwargs) -> HttpResponse:
    print(inbound_request.method)
    print(inbound_request.headers)

    print(inbound_request.COOKIES)
    if inbound_request.method == "POST":
        username = inbound_request.POST.get("username")
        password = inbound_request.POST.get("password")
        print(username, password)

    return HttpResponse(
        render(
            request=inbound_request,
            template_name="vulture/index.html",
            context={
                "hi": "google",
            },
        )
    )

vulture/templates/vulture/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Vulture</title>
    </head>
    <body>
        <form action="{% url 'vulture:index' %}" method="post" id="choiceForm">
            {% csrf_token %}
            <input type="text" name="username" id="username" />
            <input type="text" name="password" id="password" />
            <input type="button" value="Submit" id="choiceFormSubmit" />
            <input type="submit" value="Submitt" id="choiceFormSubmitt" />
        </form>
    </body>
    <script>
        let form = document.getElementById("choiceForm");
        let formSubmit = document.getElementById("choiceFormSubmit");

        formSubmit.addEventListener("click", (e) => {
            let username = document.getElementById("username");
            let password = document.getElementById("password");
            let csrftoken = document.querySelector("#choiceForm>input[name='csrfmiddlewaretoken']").value;

            cookie = document.cookie.split("=");

            let response_header = {
                "X-CSRFToken": cookie[1],
            };

            let response_body = {
                username,
                password
            };


            fetch(form.action !== "" ? form.action : window.location.href, {
                method: "POST",
                headers: response_header,
                body: response_body,
                data: response_body,
            })
                .then(
                    (response) => {
                        return response.ok;
                    },
                    (err) => {
                        console.log(err.message);
                    }
                )
                .then((result) => {
                    console.log(result, "form submitted...");
                });
        });
    </script>
</html>

<input
    type="hidden"
    name="csrfmiddlewaretoken"
    value="KMUlSoCI9Kk94ArTVkXIYiv4q2p2AMIPgHZKYN0yJZuVgIwmoqj9xZFE2JWSWQc7"
/>