Code/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("learn.urls", namespace="event_management")),
    path("vulture/", include("vulture.urls", namespace="vulture")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls", namespace="members")),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )


admin.site.site_header = "Codemy"
admin.site.site_title = "Codemy.com"
admin.site.index_title = "Learn from codemy"

learn/urls.py
from django.urls import path

from learn.view.view_calendar import calenderMonthView
from learn.view.view_event import event_add, event_delete, event_list, event_read
from learn.view.view_event import event_update
from learn.view.view_participant import participant_add, participant_delete
from learn.view.view_participant import participant_list, participant_read
from learn.view.view_participant import participant_update
from learn.view.view_venue import venue_add, venue_delete, venue_list, venue_read
from learn.view.view_venue import venue_update
from learn.view.view_venue_exports import export_venue_csv, export_venue_pdf
from learn.view.view_venue_exports import export_venue_txt
from learn.views import APIresponse, index, search

app_name = "learn"

urlpatterns = [
    # Home page
    path(
        "",
        index,
        name="index",
    ),
    path(
        "search",
        search,
        name="search",
    ),
    # Venues
    path(
        "venue_add",
        venue_add,
        name="venue_add",
    ),
    path(
        "venue_list",
        venue_list,
        name="venue_list",
    ),
    path(
        "venue_read/<uuid:venue_id>",
        venue_read,
        name="venue_read",
    ),
    path(
        "venue_update/<uuid:venue_id>",
        venue_update,
        name="venue_update",
    ),
    path(
        "venue_delete/<uuid:venue_id>",
        venue_delete,
        name="venue_delete",
    ),
    # Events
    path(
        "event_add",
        event_add,
        name="event_add",
    ),
    path(
        "event_list",
        event_list,
        name="event_list",
    ),
    path(
        "event_read/<uuid:event_id>",
        event_read,
        name="event_read",
    ),
    path(
        "event_update/<uuid:event_id>",
        event_update,
        name="event_update",
    ),
    path(
        "event_delete/<uuid:event_id>",
        event_delete,
        name="event_delete",
    ),
    # Participants
    path(
        "participant_add",
        participant_add,
        name="participant_add",
    ),
    path(
        "participant_list",
        participant_list,
        name="participant_list",
    ),
    path(
        "participant_read/<uuid:participant_id>",
        participant_read,
        name="participant_read",
    ),
    path(
        "participant_update/<uuid:participant_id>",
        participant_update,
        name="participant_update",
    ),
    path(
        "participant_delete/<uuid:participant_id>",
        participant_delete,
        name="participant_delete",
    ),
    # Export Events
    path(
        "export_venues",
        export_venue_txt,
        name="export_venues",
    ),
    path(
        "export_venues_csv",
        export_venue_csv,
        name="export_venues_csv",
    ),
    path(
        "export_venues_pdf",
        export_venue_pdf,
        name="export_venues_pdf",
    ),
    # Calendar Related Views
    path(
        "calender",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "calender/<int:year>/<int:month>",
        calenderMonthView,
        name="viewCalender",
    ),
    path(
        "api",
        APIresponse,
        name="api",
    ),
]

members/urls.py
from django.urls import path

from members.views import login_user, logout_user, register_user

app_name = "members"

urlpatterns = [
    path("register_user", register_user, name="register_user"),
    path("login", login_user, name="login"),
    path("logout", logout_user, name="logout"),
]

learn/models.py
# from django.db import models

# Create your models here.

learn/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render

from learn.model import Event, Venue
from datetime import datetime

# Create your views here.


def index(inbound_request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        render(
            request=inbound_request,
            template_name="learn/index.html",
            context={
                "title": "Codemy",
            },
        )
    )


@login_required(login_url="members:login")
def search(inbound_request: HttpRequest) -> HttpResponse:
    print("Hello Google....")
    if (inbound_request.method == "POST") and (
        search_query := inbound_request.POST.get("searched", False)
    ):
        venues = Venue.objects.filter(
            Q(name__contains=search_query) | Q(address__contains=search_query)
        )

        events = Event.objects.filter(
            Q(name__contains=search_query)
            | Q(description__contains=search_query)
            | Q()
        )
        print(search_query, venues, events)

        return HttpResponse(
            render(
                request=inbound_request,
                template_name="learn/search_results.html",
                context={
                    "title": "Codemy",
                    "venues": venues,
                    "events": events,
                    "no_of_results": len(venues) + len(events),
                },
            )
        )
    return HttpResponseBadRequest(
        content="Bad Request",
    )


def APIresponse(inbound_request:HttpRequest):
    return JsonResponse(
        {"datetime":datetime.now()}
    )

learn/templates/learn/Venue/create.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="{% static 'CSS/formcontrol.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<!--  -->
<h2>Add Venue</h2>
{% if user.is_authenticated %}
<br />
{% if is_submitted %}
<p>Form Submitted Successfully...</p>
{% else %}
<div class="userform">
    <form action="{% url 'learn:venue_add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form.as_div}}
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endif %}
<!--  -->
{% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %} {% endblock main-content %}
<!--  -->
{% block footer %}
<!--  -->
{% endblock footer %}

learn/templates/learn/Venue/delete.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="{% static 'CSS/formcontrol.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<!--  -->
{% endblock main-content %}

learn/templates/learn/Venue/read.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
{% if user.is_authenticated %}
<h3>
    <a href="{{venue.website}}"> {{venue.name}} <span class="material-symbols-outlined fs-6">
        open_in_new
        </span></a>
</h3>
<address>{{venue.address}}. {{venue.zip_code}}</address>
<p>
    <a href="tel:+{{venue.phone}}"> {{venue.phone}} </a>
</p>
<p>
    <a href="mailto:{{venue.email}}"> {{venue.email}} </a>
</p>
{% if venue.picture %}
<img src="{{venue.picture.url}}" alt="" style="width: 320px; height: 180px;object-fit: contain;">
{% endif %}
{% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %}
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %} {% endblock footer %}

learn/templates/learn/Venue/read_all.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<h2>Venues</h2>
<nav aria-label="...">
    <ul class="pagination">
        {% if venues.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{venues.previous_page_number}}">Previous</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo; First</span></li>
        <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %} {% for i in num_of_pages %} {% if i == current_page %}
        <li class="page-item active" aria-current="page"><span class="page-link">{{i}}</span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endif %} {% endfor %} {% if venues.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{venues.next_page_number}}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{venues.paginator.num_pages}}">Last &raquo;</a></li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        <li class="page-item disabled"><span class="page-link">Last &raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% for venue in venues %}
<h3><a href="{% url 'learn:venue_read' venue.id %}"> {{venue.name}} </a></h3>
<p>{{venue.address}}</p>
{% if user.is_authenticated %}
{% if user.id == venue.owner.id %}
<div style="display: flex; justify-content: flex-start; align-items: center">
    <div class="col">
        <a href="{% url 'learn:venue_update' venue.id %}">
            <button class="btn btn-secondary">Update</button>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'learn:venue_delete' venue.id %}">
            <button class="btn btn-danger">Delete</button>
        </a>
    </div>
</div>
{% endif %} {% endif %}
<hr />
{% endfor %}

<!--
    {% if venues.has_previous %}
    <a href="?page=1"> &laquo First</a>
    <a href="?page={{venues.previous_page_number}}"> Previous</a>
    {% endif %}

<span>
    {{venues.number}}
</span>

{% if venues.has_next %}
<a href="?page={{venues.next_page_number}}"> Next</a>
<a href="?page={{venues.paginator.num_pages}}"> &raquo Last</a>
{% endif %}
-->
<!--
    {{venues}}
    <br>
    {{venues.has_previous}}
    <br>
    {{venues.has_next}}
    <br>
    {{venues.number}}
    <br>
    {{venues.paginator.num_pages}}
    <br>
    <br>
-->
{% endblock main-content %}
<!--  -->
{% block footer %}
<!--  -->
{% if user.is_authenticated %}
<style>
    .footer-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-flow: column nowrap;
        width: 50%;
        margin: 0 auto;
    }
</style>
<div class="footer-container">
    <span class="content">
        <a href="{% url 'learn:export_venues' %}">Export Venues as Text</a>
    </span>
    <span class="content">
        <a href="{% url 'learn:export_venues_csv' %}">Export Venues as CSV</a>
    </span>
    <span class="content">
        <a href="{% url 'learn:export_venues_pdf' %}">Export Venues as PDF</a>
    </span>
</div>
{% endif %}
<!--  -->
{% endblock footer %}

learn/templates/learn/Venue/update.html
{% extends "base.html" %}
<!--  -->
{% load static %}
<!--  -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}" />
<link rel="stylesheet" href="{% static 'CSS/formcontrol.css' %}" />
{% endblock stylesheets %}
<!--  -->
{% block main-content %}
<!--  -->
{% if user.is_authenticated %}
<h2>Update Venue</h2>
<br />
<div class="userform">
    <form action="{% url 'learn:venue_update' venue.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!--  -->
        {{form.as_div}}
        <input class="btn btn-primary" type="submit" value="Update" />
    </form>
</div>
{% else %}
<p>You need to <a href="{% url 'members:login' %}"> Login </a> to Access this page.</p>
{% endif %}
<!--  -->
{% endblock main-content %}
<!--  -->
{% block footer %}
<!--  -->
{% endblock footer %}